platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: slim

params:
  SERVICE_ACCOUNT_JSON:
  KUBERNETES_PROJECT:
  KUBERNETES_REGION:
  KUBERNETES_CLUSTER:

run:
  path: sh
  args:
    - -exc
    - |
      apt install kubectl
      cat >~/gcloud-service-key.json << EOL
      $SERVICE_ACCOUNT_JSON
      EOL
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      #gcloud container clusters get-credentials rm-k8s-cluster --zone $KUBERNETES_REGION --project $KUBERNETES_PROJECT
      gcloud container clusters resize $KUBERNETES_CLUSTER --size 0 --region=$KUBERNETES_REGION --quiet